Modified way_data_validator, tests for Way model, views and add way_d…
Lv-365python/wayToHome pull request #30
Opened 2019-01-03 16:12 UTC by meelros

## JIRA
* https://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=933&view=detail&selectedIssue=PYTHON-199
* https://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=933&view=detail&selectedIssue=PYTHON-200

## Code reviewers

- [ ] @BoroviyOrest
- [ ] @Kardan1123
- [ ] @mizin4ik
- [ ] @dimigor
- [ ] @PetrushynskyiOleksii
- [ ] @Sasha1152

### Second Level Review

- [ ] @lhalam

## Summary of change
Modified way_data_validator, tests for Way model, views and add way_data_validator to way/views.py

## CHECKLIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out a user if needed
- [ ]  PR meets all conventions

2019-01-04 12:12 UTC, BoroviyOrest submitted a review, later dismissed
All is good

2019-01-04 12:20 UTC, MaxDubchak requested changes

2019-01-04 12:20 UTC, Kardan1123 commented on way_to_home/tests/unittests/way/testmodel.py
> +
longtitude must be between -180 and 180, and latitude must be betweent -90 and 90, else you might run into issues with place_data_validator

2019-01-04 12:20 UTC, Kardan1123 commented on way_to_home/tests/unittests/way/testmodel.py
> +			position=0, way=self.way,
why are those in one line?

2019-01-04 12:20 UTC, Kardan1123 commented on way_to_home/tests/unittests/way/testmodel.py
> +		way = Way.create(user=user)
In create also test passing in name

2019-01-04 12:25 UTC, meelros commented on way_to_home/tests/unittests/way/testmodel.py
> +			position=0, way=self.way,
it was a mistake, changed

2019-01-04 12:25 UTC, meelros commented on way_to_home/tests/unittests/way/testmodel.py
> +
done

2019-01-04 12:30 UTC, meelros commented on way_to_home/tests/unittests/way/testmodel.py
> +		way = Way.create(user=user)
done

2019-01-04 12:39 UTC, BoroviyOrest submitted a review, later dismissed

2019-01-04 12:49 UTC, MaxDubchak submitted a review, later dismissed

2019-01-04 13:02 UTC, Sasha1152 submitted a review, later dismissed
Good!

2019-01-08 11:48 UTC, victoria-kit approved these changes
Good!

2019-01-08 11:50 UTC, lhalam approved these changes

2019-01-08 11:51 UTC, merged