Feature/create notification test
Lv-365python/wayToHome pull request #32
Opened 2019-01-04 16:59 UTC by mizin4ik

## JIRA

* https://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=933&view=detail&selectedIssue=PYTHON-214
* https://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=933&view=detail&selectedIssue=PYTHON-213

## Code reviewers

- [ ] @meelros
- [ ] @BoroviyOrest
- [ ] @Kardan1123
- [ ] @dimigor
- [ ] @PetrushynskyiOleksii
- [ ] @Sasha1152

### Second Level Review

- [ ] @lhalam

## Summary of change

ToDo
Modified notification validation, 
Create tests for Notification model, 
Create tests for Notification views 
Replace responses in Notification View to constants

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2019-01-04 19:06 UTC, PetrushynskyiOleksii requested changes
You also should test the next lines of code::

- in `PUT`:

    ```
    if not way == notification.way: 
      return RESPONSE_403_ACCESS_DENIED
    ```
- in `POST`:

    ```
    if not user == way.user:
        return RESPONSE_403_ACCESS_DENIED
    ```
- in `DELETE`
    ```
     if not way == notification.way:
        return RESPONSE_403_ACCESS_DENIED
   ```

2019-01-08 10:24 UTC, dimigor commented on way_to_home/notification/views.py
> +        if not (way and notification_id):
Must be `or`.
In your case this return handles when two variables are False, but we need when even one is False

2019-01-08 10:24 UTC, dimigor commented on way_to_home/notification/views.py
> +        if not (way and notification_id):
Same as above

2019-01-08 10:24 UTC, dimigor commented on way_to_home/tests/unittests/notification/testviews.py
> +        user = CustomUser(id=100, email='testuser@mail.com', is_active=True)
use `CustomUser.objects.create`

2019-01-08 10:24 UTC, dimigor commented on way_to_home/tests/unittests/notification/testviews.py
> +    def test_post_from_another_way(self):
I think this method should be named as "test_post_from_non_existing_way"
Also, add test when way exist, but the user is not the owner, and check if `response.status_code` equals to 403

2019-01-08 11:09 UTC, mizin4ik commented on way_to_home/tests/unittests/notification/testviews.py
> +    def test_post_from_another_way(self):
done, thank's

2019-01-08 11:11 UTC, mizin4ik commented on way_to_home/tests/unittests/notification/testviews.py
> +        user = CustomUser(id=100, email='testuser@mail.com', is_active=True)
With CustomUser.objects.create user can't login.

2019-01-08 13:05 UTC, mizin4ik commented on way_to_home/notification/views.py
> +        if not (way and notification_id):
done. I change to "if not way or not notification_id:"

2019-01-08 13:05 UTC, mizin4ik commented on way_to_home/notification/views.py
> +        if not (way and notification_id):
done

2019-01-08 13:05 UTC, mizin4ik commented on way_to_home/tests/unittests/notification/testviews.py
> +        user = CustomUser(id=100, email='testuser@mail.com', is_active=True)
done

2019-01-08 13:08 UTC, dimigor submitted a review, later dismissed

2019-01-08 13:09 UTC, PetrushynskyiOleksii submitted a review, later dismissed

2019-01-09 10:48 UTC, dimigor approved these changes

2019-01-09 10:53 UTC, meelros approved these changes
All is good!

2019-01-09 10:53 UTC, Sasha1152 approved these changes

2019-01-09 10:53 UTC, merged