Notification `get_expired` method tests
Lv-365python/wayToHome pull request #50
Opened 2019-01-15 21:36 UTC by PetrushynskyiOleksii

## Code reviewers

- [ ] @meelros
- [ ] @BoroviyOrest
- [ ] @Kardan1123
- [ ] @mizin4ik
- [ ] @dimigor 
- [ ] @Sasha1152

### Second Level Review

- [ ] @lhalam

## Summary of change

- Add tests for `get_expired` method of Notification model

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2019-01-15 22:08 UTC, MaxDubchak requested changes

2019-01-15 22:08 UTC, MaxDubchak commented on way_to_home/tests/unittests/notification/testmodel.py
> +        self.way = Way.objects.get(id=100)
whu don't you assign it to self.way upon creation?

2019-01-15 22:23 UTC, PetrushynskyiOleksii commented on way_to_home/tests/unittests/notification/testmodel.py
> +        self.way = Way.objects.get(id=100)
You are right, thank u

2019-01-15 22:25 UTC, MaxDubchak approved these changes

2019-01-16 10:21 UTC, dimigor approved these changes

2019-01-16 10:22 UTC, merged