Feature/create logout view
Lv-365python/wayToHome pull request #60
Opened 2019-01-17 16:35 UTC by BoroviyOrest

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=216)

## Code reviewers

- [ ] @meelros
- [ ] @Kardan1123
- [ ] @mizin4ik
- [ ] @dimigor
- [ ] @PetrushynskyiOleksii
- [ ] @Sasha1152

### Second Level Review

- [ ] @lhalam

## Summary of change

Add logout view and test for it, add cookies in login

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2019-01-17 20:31 UTC, vo333ua commented on way_to_home/custom_user/views.py
> +        response.set_cookie('user_id', user.id, max_age=TTL_USER_ID_COOKIE)
for what do you need to save user id in cookie?

2019-01-18 08:06 UTC, MaxDubchak requested changes

2019-01-18 08:06 UTC, Kardan1123 commented on way_to_home/tests/unittests/custom_user/testviews.py
> +        self.assertEqual(response.status_code, 200)
I'd advice you just use
`self.client.login(...)`

2019-01-21 12:13 UTC, dimigor submitted a review, later dismissed

2019-01-21 12:20 UTC, Sasha1152 submitted a review, later dismissed

2019-01-21 16:45 UTC, Kardan1123 commented on way_to_home/tests/unittests/custom_user/testviews.py
> +        self.assertEqual(response, True)
remove assert, rename test_data  to login_credentials, don't store returned value of login method

2019-01-21 17:10 UTC, MaxDubchak submitted a review, later dismissed
I approve

2019-01-21 22:25 UTC, Sasha1152 submitted a review, later dismissed
Good!

2019-01-22 14:34 UTC, meelros approved these changes

2019-01-22 14:34 UTC, Sasha1152 approved these changes

2019-01-22 14:34 UTC, dimigor approved these changes

2019-01-22 14:39 UTC, merged