add modal map represents way from A to B
Lv-365python/wayToHome pull request #91
Opened 2019-01-28 14:50 UTC by dimigor

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/PYTHON-264)

## Code reviewers

- [ ] @meelros
- [ ] @BoroviyOrest
- [ ] @Kardan1123
- [ ] @mizin4ik
- [ ] @PetrushynskyiOleksii
- [ ] @Sasha1152

## Summary of change
add modal map represents way from A to B

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2019-01-28 19:59 UTC, PetrushynskyiOleksii requested changes

2019-01-28 19:59 UTC, PetrushynskyiOleksii commented on way_to_home/tests/unittests/way/testviews.py
> -		response_dict['routes'][0].pop('end_place')
You can't predict which ids will return. So you should remove from expected dictionary and response all ids. Because later it can easily fail.

2019-01-29 12:08 UTC, lhalam submitted a review, later dismissed

2019-01-29 12:14 UTC, PetrushynskyiOleksii submitted a review, later dismissed

2019-01-29 12:56 UTC, Sasha1152 approved these changes

2019-01-29 12:57 UTC, victoria-kit approved these changes

2019-01-29 12:57 UTC, merged